const sapData = {
    id: 233,
    BLDAT: '2025-11-22',
    XBLNR: 'DC/ERD-GS/0001',
    ZTO: 'Plot No.: R-43, Krishi Nutrition Company Private Limited, Sipcot Industrial Growth Center,Perundurai, Erode, Tamil Nadu,638052,33AAFCK3415K1ZO',
    ZADDRESS: 'Krishi Nutrition Company Private Limited, C/o Railway Goodshed, Erode, Erode, Tamil Nadu,638002,33AAFCK3415K1ZO',
    ZTRUCK_NO: 'TN 33 U 5619',
    MAKTX: 'MAIZE',
    MATNR: 32,
    ZHSN_CODE: '10059000',
    MENGE_D: '20.000',
    ZRATE: '20900.00',
    ZCGST_PER: '0.00',
    ZSGST_PER: '0.00',
    ZTAXABLE_VAL: '418000.00',
    ZCGST_AMT: '0.00',
    ZSGST_AMT: '0.00',
    ZGROSS_AMT: '418000.00',
    ZEWAY: '',
    ZSD_DISTANCE: 0,
    ZSTATUS: 'Active',
    ZREASON: '-',
    ZPO_NO: '4600000563',
    ZNO_OF_BAGS: '380',
    ZRR_NO: '282000119/AYB'
}


Error_Eway_Bill_Payload = {
    supplyType: 'I',
    subSupplyType: '5',
    subSupplyDesc: 'For Own Use',
    docType: 'CHL',
    docNo: 'DC/BGE/00004',
    docDate: '07/01/2026',
    fromGstin: '29AABCR7796N000',
    fromTrdName: 'Bharat Feeds Private Limited',
    fromAddr1: 'Bharat Feeds Private Limited, Industrial Area, Peenya 2nd Stage',
    fromAddr2: 'Bengaluru, Karnataka, 560058',
    fromPlace: 'Karnataka',
    fromPincode: 560058,
    actFromStateCode: '29',
    fromStateCode: '29',
    toGstin: '29AABCR7796N000',
    toTrdName: 'Bharat Feeds Private Limited',
    toAddr1: 'Shree Agro Suppliers, Shed No 12',
    toAddr2: 'Gokul Road Industrial Estate, Hubballi, Karnataka, 580030',
    toPlace: 'Hubballi',
    toPincode: 580030,
    actToStateCode: '29',
    toStateCode: '29',
    transactionType: 1,
    otherValue: 0,
    totalValue: 2,
    cgstValue: 0,
    sgstValue: 0,
    igstValue: 0,
    cessValue: 0,
    cessNonAdvolValue: 0,
    totInvValue: 2,
    transporterId: '',
    transporterName: '',
    transDocNo: 'DC/BGE/00004',
    transMode: '1',
    transDistance: 0,
    transDocDate: '07/01/2026',
    vehicleNo: 'TN10AB1020',
    vehicleType: 'R',
    ItemList: [
        {
            productName: 'JOWAR',
            productDesc: 'JOWAR',
            hsnCode: '10082110',
            quantity: 1.999,
            qtyUnit: 'KG',
            taxableAmount: 2,
            sgstRate: 0,
            cgstRate: 0,
            igstRate: 0,
            cessRate: 0,
            cessNonAdvol: 0
        }
    ]
}

Maize_Eway_Bill_Payload = {
    supplyType: 'I',
    subSupplyType: '5',
    subSupplyDesc: 'For Own Use',
    docType: 'CHL',
    docNo: 'DC/BGT/00003',
    docDate: '07/01/2026',
    fromGstin: '29AABCR7796N000',
    fromTrdName: 'Bharat Feeds Private Limited',
    fromAddr1: 'Bharat Feeds Private Limited, Industrial Area, Peenya 2nd Stage',
    fromAddr2: 'Bengaluru, Karnataka, 560058',
    fromPlace: 'Karnataka',
    fromPincode: 560058,
    actFromStateCode: '29',
    fromStateCode: '29',
    toGstin: '29AABCR7796N000',
    toTrdName: 'Bharat Feeds Private Limited',
    toAddr1: 'Shree Agro Suppliers, Shed No 12',
    toAddr2: 'Gokul Road Industrial Estate, Hubballi, Karnataka, 580030',
    toPlace: 'Hubballi',
    toPincode: 580030,
    actToStateCode: '29',
    toStateCode: '29',
    transactionType: 1,
    otherValue: 0,
    totalValue: 66633,
    cgstValue: 1665.83,
    sgstValue: 1665.83,
    igstValue: 0,
    cessValue: 0,
    cessNonAdvolValue: 0,
    totInvValue: 69964.99,
    transporterId: '',
    transporterName: '',
    transDocNo: 'DC/BGT/00003',
    transMode: '1',
    transDistance: 0,
    transDocDate: '07/01/2026',
    vehicleNo: 'TN10AB1020',
    vehicleType: 'R',
    ItemList: [
        {
            productName: 'SOYA DOC STOCK',
            productDesc: 'SOYA DOC STOCK',
            hsnCode: '23040030',
            quantity: 1.999,
            qtyUnit: 'MTS',
            taxableAmount: 66633.33,
            sgstRate: 2.5,
            cgstRate: 2.5,
            igstRate: 0,
            cessRate: 0,
            cessNonAdvol: 0
        }
    ]
}

